# Generated by Django 3.1.6 on 2021-02-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_poster',
            new_name='date_posted',
        ),
    ]
